config/routes.rb
Rails.application.routes.draw do
  # get 'lists/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id,
    message: "has already been added to this list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  validates :image_url, presence: true, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), message: "must be a valid URL" }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  # validates :poster_url, presence: true
  # validates :rating, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @bookmark = Bookmark.new
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #cac4c4ff;">
  <div class="container-fluid d-flex align-items-center justify-content-between">
    <a class="navbar-brand d-flex align-items-center" href="#">
      <%= image_tag "popcorn.png", alt: "Popcorn", style: "height: 50px;" %>
      <span class="ms-2">Watch List</span>
    </a>

    <ul class="nav">
      <li class="nav-item">
        <%= link_to "My Lists", lists_path, class: "nav-link active", aria: { current: "page" } %>
      </li>
      <li class="nav-item">
        <%= link_to "New List", new_list_path, class: "nav-link active", aria: { current: "page" } %>
      </li>
    </ul>
  </div>
</nav>
<%= simple_form_for @bookmark do |f| %>
  <%= f.association :movie %>
  <%= f.association :list %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #cac4c4ff;">
  <div class="container-fluid d-flex align-items-center justify-content-between">
    <a class="navbar-brand d-flex align-items-center" href="#">
      <%= image_tag "popcorn.png", alt: "Popcorn", style: "height: 50px;" %>
      <span class="ms-2">Watch List</span>
    </a>

    <ul class="nav">
      <li class="nav-item">
        <%= link_to "My Lists", lists_path, class: "nav-link active", aria: { current: "page" } %>
      </li>
      <li class="nav-item">
        <%= link_to "New List", new_list_path, class: "nav-link active", aria: { current: "page" } %>
      </li>
    </ul>
  </div>
</nav>

<ul>
  <% @lists.each do |list| %>
    <li><%= list.name %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #cac4c4ff;">
  <div class="container-fluid d-flex align-items-center justify-content-between">
    <a class="navbar-brand d-flex align-items-center" href="#">
      <%= image_tag "popcorn.png", alt: "Popcorn", style: "height: 50px;" %>
      <span class="ms-2">Watch List</span>
    </a>

    <ul class="nav">
      <li class="nav-item">
        <%= link_to "My Lists", lists_path, class: "nav-link active", aria: { current: "page" } %>
      </li>
      <li class="nav-item">
        <%= link_to "New List", new_list_path, class: "nav-link active", aria: { current: "page" } %>
      </li>
    </ul>
  </div>
</nav>

<div class="mt-3 mb-4">
  <%= image_tag "Screenshot 2025-10-21 at 21.41.49.png", alt: "list", class: "img-fluid w-100" %>
</div>

<div class="container-lg">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <%= simple_form_for @list do |f| %>
        <div class="mb-3">
          <%= f.input :name %>
          <%= f.input :image_url, as: :url, placeholder: "Enter image URL" %>
        </div>
        <%= f.submit "Create List", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/lists/show.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #cac4c4ff;">
  <div class="container-fluid d-flex align-items-center justify-content-between">
    <a class="navbar-brand d-flex align-items-center" href="#">
      <%= image_tag "popcorn.png", alt: "Popcorn", style: "height: 50px;" %>
      <span class="ms-2">Watch List</span>
    </a>

    <ul class="nav">
      <li class="nav-item">
        <%= link_to "My Lists", lists_path, class: "nav-link active", aria: { current: "page" } %>
      </li>
      <li class="nav-item">
        <%= link_to "New List", new_list_path, class: "nav-link active", aria: { current: "page" } %>
      </li>
    </ul>
  </div>
</nav>

<h2><%= @list.name %></h2>
<% if @list.image_url.present? %>
  <%= image_tag @list.image_url, alt: @list.name, class: "img-fluid" %>
<% end %>